<script>
 import { onMount } from 'svelte';
 import { previewSheet, commitSheet, extractSets } from './sheet-scan.js';
 import { Asterisk, ArrowUpRight, Plus, Search, X, Upload, RefreshCw, FileSpreadsheet, Image as ImageIcon, Check, ArrowRight, LogOut, ChevronLeft, ChevronRight, CircleAlert, Pencil, LoaderCircle } from '@lucide/svelte';
 let token=$state(''), authenticated=$state(false), authenticating=$state(false), loginError=$state('');
 let tab=$state('catalog'), sets=$state([]), facets=$state({total:0,ready:0,groups:[]}), q=$state(''), group=$state(''), page=$state(1), total=$state(0), loading=$state(false);
 let editImages=$state([]), originalExample=$state(''), ingestion=$state({intervalSeconds:20,pausedUntil:'',reason:''});
 let message=$state(''), error=$state(''), busy=$state(false), editor=$state(false), editID=$state(0), form=$state(blank()), files=$state([]);
 let sheetUrl=$state('https://docs.google.com/spreadsheets/d/1z45mKRtLvTZth8b-uhqkMyjzxVtHI8b7YVcySQVeEkg/edit?gid=0'), csvFile=$state(null), report=$state(null);
 let importPreview=$state(null), pendingScanIds=$state([]);
 let extracting=$state(false), progress=$state({done:0,total:0,ready:0,failed:0}), current=$state(''), stopRequested=$state(false), logs=$state([]);
 let debounce, requestSequence=0;
 const galleryURL=import.meta.env.VITE_GALLERY_URL || 'http://localhost:5173';
 const missing=$derived(Math.max(0,facets.total-(facets.complete||0)));
 const gankPaused=$derived(Boolean(ingestion.pausedUntil&&Date.parse(ingestion.pausedUntil)>Date.now()));
 function isGankExample(example){try{const host=new URL(example).hostname.replace(/\.$/,'');return host==='ganknow.com'||host.endsWith('.ganknow.com');}catch{return false;}}
 function blank(){return {title:'',group:'',date:'',source:'',example:'',notes:''};}
 async function api(path,options={}) {
  const response=await fetch(`/api${path}`,{...options,headers:{Authorization:`Bearer ${token}`,...options.headers}});
  const result=await response.json();if(response.status===429&&result.pausedUntil)ingestion={...ingestion,pausedUntil:result.pausedUntil,reason:result.error};if(response.status===401){authenticated=false;throw new Error('Administrator token is invalid. Sign in again.');}if(!response.ok){const failure=new Error(result.error||'Request failed');failure.pausedUntil=result.pausedUntil;throw failure;}return result;
 }
 async function login(e){e.preventDefault();authenticating=true;loginError='';try{await api('/admin/status');authenticated=true;await load();}catch(e){loginError=e.message;}finally{authenticating=false;}}
 async function load(){
  const seq=++requestSequence;loading=true;
  try{const query=new URLSearchParams({q,group,page:String(page),limit:'40'});const [result,f,status]=await Promise.all([api(`/sets?${query}`),api('/facets'),api('/admin/ingestion')]);if(seq!==requestSequence)return;sets=result.items;total=result.total;facets=f;ingestion=status;}
  catch(e){if(seq===requestSequence)error=e.message;}finally{if(seq===requestSequence)loading=false;}
 }
 function search(){page=1;clearTimeout(debounce);debounce=setTimeout(load,250);}
 onMount(()=>()=>{clearTimeout(debounce);stopRequested=true;});
 function newSet(){form=blank();editID=0;editImages=[];originalExample='';files=[];editor=true;message='';error='';}
 function edit(set){form={title:set.title,group:set.group,date:set.date,source:set.source,example:set.example,notes:set.notes};editID=set.id;editImages=set.images;originalExample=set.example;files=[];editor=true;message='';error='';}
 async function save(e){
  e.preventDefault();error='';const existing=form.example===originalExample?editImages.length:0;if(files.length&&(files.length+existing<2||files.length+existing>5)){error=`Each set needs 2–5 images. ${existing} stored, ${files.length} selected.`;return;}busy=true;let saved;
  try{saved=await api(editID?`/admin/sets/${editID}`:'/admin/sets',{method:editID?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});editID=saved.id;
   if(files.length){const body=new FormData();for(const file of files)body.append('images',file);saved=await api(`/admin/sets/${saved.id}/images`,{method:'POST',body});}
   else if(form.example.startsWith('https://')&&saved.images.length<2&&!(gankPaused&&isGankExample(form.example))){saved=await api(`/admin/sets/${saved.id}/extract?target=2`,{method:'POST'});}
   editor=false;message=`Saved “${saved.title}”. ${saved.images.length<2?`${saved.images.length}/5 images; needs at least 2. ${saved.imageError||'Add images or extract from the example post.'}`:`${saved.images.length}/5 images stored.`}`;await load();
  }catch(e){error=`${saved?'Metadata was saved. ':''}${e.message}`;}finally{busy=false;}
 }
 async function retry(set){busy=true;error='';message='';try{const result=await api(`/admin/sets/${set.id}/extract`,{method:'POST'});message=result.images.length>=2?`${result.images.length}/5 images stored for “${set.title}”.`:`${set.title}: ${result.imageError}`;await load();}catch(e){error=e.message;}finally{busy=false;}}
 async function reviewImport(csv=null){
  busy=true;message='';error='';
  try{importPreview=await previewSheet(api,sheetUrl,csv);}
  catch(e){error=e.message;}finally{busy=false;}
 }
 function importSheet(e){e.preventDefault();reviewImport(csvFile);}
 function batchOptions(){return {shouldStop:()=>stopRequested||!authenticated,onCurrent:id=>current=`Set #${id}`,onProgress:batch=>{progress={done:batch.done,total:batch.total,ready:batch.ready,failed:batch.failed};logs=[...batch.results].reverse().slice(0,100);}};}
 function finishBatch(batch){
  pendingScanIds=batch.remaining;
  if(batch.pause)error=batch.pause.message;
  return batch.stopped?`Image extraction paused. ${batch.ready} ready; ${batch.remaining.length} sets left. Saved metadata and images are retained.`:`Images finished: ${batch.ready} ready, ${batch.failed} unavailable.`;
 }
 async function confirmImport(){
  if(!importPreview||busy)return;
  const reviewed=importPreview;busy=true;error='';stopRequested=false;logs=[];progress={done:0,total:0,ready:0,failed:0};
  try{
   const result=await commitSheet(api,reviewed,{...batchOptions(),onImport:imported=>{report=imported;pendingScanIds=imported.scanCandidates;importPreview=null;tab='import';extracting=true;message=`Imported ${imported.total} rows: ${imported.created} new, ${imported.updated} updated.`;}});
   message=`Imported ${result.report.total} rows: ${result.report.created} new, ${result.report.updated} updated. ${finishBatch(result.batch)}`;
  }catch(e){error=e.message;}finally{busy=false;extracting=false;current='';await load();}
 }
 async function resumeImported(){
  extracting=true;stopRequested=false;error='';logs=[];
  try{const batch=await extractSets(api,pendingScanIds,{...batchOptions(),target:5});message=finishBatch(batch);}
  catch(e){error=e.message;}finally{extracting=false;current='';await load();}
 }
 async function extractMissing(){
  extracting=true;stopRequested=false;error='';logs=[];
  try{let ids=report?.candidates;if(!ids){ids=[];let p=1;for(;;){const result=await api(`/sets?limit=200&page=${p}`);ids.push(...result.items.filter(x=>x.images.length<2).map(x=>x.id));if(p*200>=result.total)break;p++;}}
   const batch=await extractSets(api,ids,{...batchOptions(),target:2});
   if(batch.pause)error=batch.pause.message;
   message=batch.stopped?'Extraction paused. Saved previews are retained.':`Extraction finished: ${batch.ready} ready, ${batch.failed} unavailable.`;report=null;await load();
  }catch(e){error=e.message;}finally{extracting=false;current='';}
 }
 function signOut(){stopRequested=true;authenticated=false;token='';sets=[];message='';error='';importPreview=null;report=null;pendingScanIds=[];}
 function modal(node){node.showModal();return {destroy(){node.close();}};}
</script>

<svelte:head><title>BIAS — Back office</title></svelte:head>
<header><a class="brand" href={galleryURL}><span class="brand-mark"><Asterisk size={25}/></span>BIAS<span>®</span><small>BACK OFFICE</small></a><div class="header-actions"><a href={galleryURL} target="_blank" rel="noreferrer">View gallery <ArrowUpRight size={15}/></a>{#if authenticated}<button onclick={signOut} disabled={busy||extracting}><LogOut size={15}/> Sign out</button>{/if}</div></header>
{#if !authenticated}
 <main class="login-layout"><div class="login-intro"><div class="eyebrow">BEHIND THE COLLECTION</div><h1>Good moments.<br/><em>In good hands.</em></h1><p>Your workspace for keeping the archive growing.<br/>Add sets, bring in your sheet, and keep every preview in focus.</p><div class="login-decoration"><Asterisk size={90} strokeWidth={1}/><span>FOR THE FANS.<br/>BY THE COLLECTORS.</span></div></div><form class="login-card" onsubmit={login}><span class="lock-label">ADMINISTRATOR ACCESS</span><h2>Welcome back.</h2><p>Enter the administrator token configured for this server.</p><label>Administrator token<input type="password" autocomplete="current-password" bind:value={token} required placeholder="Your access token"/></label>{#if loginError}<div class="alert error" role="alert">{loginError}</div>{/if}<button class="primary" disabled={authenticating}>{authenticating?'Checking access…':'Open the workspace'} <ArrowRight size={17}/></button><p class="login-note">Your token stays in this browser tab's memory. Closing or refreshing the page signs you out.</p></form></main>
{:else}
 <main class="workspace"><div class="page-heading"><div><div class="eyebrow">COLLECTION WORKSPACE</div><h1>The back office<span>.</span></h1><p>A little care for every moment in the archive.</p></div><div class="heading-actions"><button class="primary" onclick={()=>reviewImport()} disabled={busy||extracting||pendingScanIds.length>0}><FileSpreadsheet size={17}/>{extracting?'Fetching images…':busy?'Reading sheet…':'Scan Google Sheet & import'}</button><button class="primary secondary" onclick={newSet} disabled={busy||extracting}><Plus size={17}/> Add image set</button></div></div>
 <div class="stats-grid"><div><span>IMAGE SETS</span><strong>{facets.total}</strong><small>Records in your collection</small></div><div><span>ARTISTS & GROUPS</span><strong>{facets.groups.length}</strong><small>A growing roster of favorites</small></div><div><span>SETS WITH 2–5 IMAGES</span><strong>{facets.complete||0}<i><Check size={19}/></i></strong><small>Stored locally in the archive</small></div><div><span>NEEDS MORE IMAGES</span><strong>{missing}</strong><small>Sets with fewer than 2 images</small></div></div>
 <nav class="tabs" aria-label="Workspace sections"><button class:active={tab==='catalog'} onclick={()=>tab='catalog'}><ImageIcon size={15}/> Image sets <span>{facets.total}</span></button><button class:active={tab==='import'} onclick={()=>tab='import'}><FileSpreadsheet size={15}/> Import & previews</button></nav>
 {#if gankPaused}<div class="alert error" role="status"><CircleAlert size={17}/>Gank ingestion paused until {new Date(ingestion.pausedUntil).toLocaleString()}. Uploads and browsing remain available.</div>{/if}
 {#if error}<div class="alert error" role="alert"><CircleAlert size={17}/>{error}<button aria-label="Dismiss error" onclick={()=>error=''}><X size={14}/></button></div>{/if}{#if message}<div class="alert success" role="status"><Check size={17}/>{message}<button aria-label="Dismiss message" onclick={()=>message=''}><X size={14}/></button></div>{/if}
 {#if tab==='catalog'}
 <section class="catalog-panel"><div class="panel-toolbar"><label class="search"><Search size={16}/><input aria-label="Search sets" placeholder="Search by artist, title, or source…" bind:value={q} oninput={search}/></label><label class="group-filter">Artist<select aria-label="Filter by group" bind:value={group} onchange={()=>{page=1;load();}}><option value="">All artists</option>{#each facets.groups as f}<option value={f.name}>{f.name}</option>{/each}</select></label><button class="icon-btn" onclick={load} aria-label="Refresh catalog" disabled={busy||extracting}><RefreshCw size={16}/></button></div>
 <div class="table-wrap"><table><thead><tr><th>SET_ID</th><th>IMAGE SET</th><th>ARTIST</th><th>DATE</th><th>PREVIEW</th><th class="right">MANAGE</th></tr></thead><tbody>{#if loading}<tr><td colspan="6" class="table-status">Loading the collection…</td></tr>{:else if !sets.length}<tr><td colspan="6" class="table-status">No sets match your filters.</td></tr>{:else}{#each sets as set}<tr><td class="set-id">{set.id}</td><td><div class="set-cell">{#if set.images.length}<img src={set.images[0].url} alt="" loading="lazy"/>{:else}<span class="thumb-placeholder"><ImageIcon size={17}/></span>{/if}<div><button class="set-title" onclick={()=>edit(set)} disabled={busy||extracting}>{set.title}</button><small>{set.source||'Source unlisted'} · {set.origin}</small></div></div></td><td><span class="artist-tag">{set.group}</span></td><td class="date">{set.date||'Unknown'}</td><td><span class="status-tag {set.images.length>=2?'ready':'pending'}" title={set.imageError}>{set.images.length}/5 {set.images.length>=2?'ready':'needs 2+'}</span>{#if set.importWarning}<small class="warning-label" title={set.importWarning}>Date needs review</small>{/if}</td><td><div class="row-actions">{#if set.images.length<5&&set.example.startsWith('https://')}<button onclick={()=>retry(set)} disabled={busy||extracting||(gankPaused&&isGankExample(set.example))} aria-label={`Retry preview for ${set.title}`} title="Retry extraction"><RefreshCw size={14}/></button>{/if}<button onclick={()=>edit(set)} disabled={busy||extracting} aria-label={`Edit ${set.title}`} title="Edit set"><Pencil size={14}/></button>{#if set.example.startsWith('https://')}<a href={set.example} target="_blank" rel="noreferrer" aria-label={`Open example for ${set.title}`} title="Open example post"><ArrowUpRight size={15}/></a>{/if}</div></td></tr>{/each}{/if}</tbody></table></div>
 <div class="pagination"><span>{total} matching sets</span><div><button disabled={page===1||loading} aria-label="Previous page" onclick={()=>{page--;load();}}><ChevronLeft size={16}/></button><span>{page} / {Math.max(1,Math.ceil(total/40))}</span><button disabled={page*40>=total||loading} aria-label="Next page" onclick={()=>{page++;load();}}><ChevronRight size={16}/></button></div></div></section>
 {:else}
 <div class="import-grid"><section class="import-card"><span class="section-number">01 / METADATA</span><FileSpreadsheet size={27} strokeWidth={1.3}/><h2>Bring your sheet.</h2><p>Scan your Google Sheet or CSV, review the changes, then confirm to import and fetch up to 5 images for new or changed examples.</p><form onsubmit={importSheet}><label>Google Sheet URL<input type="url" bind:value={sheetUrl} required disabled={busy||extracting||pendingScanIds.length>0}/></label><label class="upload-label"><Upload size={17}/><span>{csvFile?csvFile.name:'Or choose an exported CSV'}</span><input aria-label="Upload CSV" type="file" accept=".csv,text/csv" onchange={e=>csvFile=e.currentTarget.files?.[0]||null}/></label>{#if csvFile}<button type="button" class="text-btn" onclick={()=>csvFile=null}><X size={12}/> Use live Sheet instead</button>{/if}<button class="primary" disabled={busy||extracting||pendingScanIds.length>0}>{busy?'Reading…':csvFile?'Import CSV':'Preview Google Sheet import'}<ArrowRight size={16}/></button></form><div class="template-note"><strong>Template columns</strong><code>Date, Name, GROUP, Source, Example, REMARK</code><span>Date: YYMMDD or YYYY-MM-DD. Optional ID supports stable identity when renaming rows. Blank/0 dates stay unknown. Every source column is preserved.</span><span>Without ID, identity uses group + raw date + name. Renaming this tuple creates a new entry. Import is additive; rows absent from the new Sheet remain.</span><a href="/template.csv" download>Download CSV template <ArrowUpRight size={13}/></a></div></section>
 <section class="import-card"><span class="section-number">02 / PREVIEW IMAGES</span><ImageIcon size={27} strokeWidth={1.3}/><h2>Put faces to sets.</h2><p>Read up to 5 public images from each example post and store them in SQLite. Missing or deleted posts keep their metadata.</p>{#if report}<div class="report"><div><strong>{report.created}</strong><span>NEW</span></div><div><strong>{report.updated}</strong><span>UPDATED</span></div><div><strong>{report.scanCandidates.length}</strong><span>NEW PREVIEWS</span></div></div>{/if}
 {#if pendingScanIds.length}<button class="primary" onclick={resumeImported} disabled={busy||extracting}><RefreshCw size={16}/>Continue imported previews ({pendingScanIds.length})</button>{/if}
 <button class="primary secondary" onclick={extractMissing} disabled={busy||extracting||missing===0||gankPaused}><RefreshCw size={16} class={extracting?'spin':''}/>{extracting?'Extracting previews…':`Extract ${report?.candidates.length??missing} incomplete sets`}</button>
 {#if extracting||progress.total}<div class="extraction-progress"><div><span>{extracting?current:'Last extraction'}</span><span>{progress.done} / {progress.total}</span></div><progress value={progress.done} max={progress.total||1}></progress><p>{progress.ready} ready · {progress.failed} unavailable</p>{#if extracting}<button class="text-btn" onclick={()=>stopRequested=true} disabled={stopRequested}>{stopRequested?'Stopping after current set…':'Stop after current set'}</button>{/if}</div>{/if}
 <div class="template-note"><strong>Gank request pacing</strong><span>At least {ingestion.intervalSeconds} seconds between requests, shared across Gank subdomains. Local budget: {ingestion.requestsRemaining??60}/{ingestion.dailyRequests??60} requests remaining per 24 hours. Cached posts last 7 days. Confirmed Sheet imports target 5 images for new or changed examples. Keep this tab open while fetching. Bulk extraction targets 2 images per set; individual retries can fill up to 5. A 429 or 403 stops the batch and saves a cooldown across restarts.</span><span>Only publicly accessible raster images are ingested. A failure stays visible and can be retried here or corrected with a manual image upload.</span></div></section></div>
 {#if logs.length}<section class="log-panel"><h3>Extraction results <span>Most recent first</span></h3>{#each logs as log}<div class="log-row"><span class="status-tag {log.state}">{log.state}</span><strong>set_id: {log.id} · {log.title}</strong><span>{log.detail||'Preview stored in SQLite'}</span></div>{/each}</section>{/if}
 {/if}
 <footer><Asterisk size={15}/><span>BIAS / COLLECTION WORKSPACE</span><span>Every moment has a place.</span></footer>
 </main>
{/if}

{#if editor}<div class="modal-backdrop" role="presentation" onclick={()=>{if(!busy)editor=false;}}></div><dialog use:modal oncancel={e=>{e.preventDefault();if(!busy)editor=false;}} aria-label={editID?'Edit image set':'Add image set'}><div class="editor-heading"><div><span class="eyebrow">{editID?`ARCHIVE / ${String(editID).padStart(4,'0')}`:'A NEW MOMENT'}</span><h2>{editID?'Edit image set.':'Grow the collection.'}</h2></div><button class="icon-btn" aria-label="Close editor" disabled={busy} onclick={()=>editor=false}><X size={20}/></button></div><form onsubmit={save}>{#if editID}<label>set_id<input value={editID} readonly aria-label="set_id" aria-describedby="set-image-help"/><small id="set-image-help">{editImages.length}/5 images stored. A complete set needs at least 2.</small></label>{/if}<label>Set title<input bind:value={form.title} required maxlength="500" placeholder="260915 Karina — Hamilton"/></label><div class="form-row"><label>Group / artist<input bind:value={form.group} list="artist-names" required maxlength="150" placeholder="aespa"/><datalist id="artist-names">{#each facets.groups as f}<option value={f.name}></option>{/each}</datalist></label><label>Date of set<input type="date" bind:value={form.date}/></label></div><label>Source<input bind:value={form.source} maxlength="300" placeholder="Photographer or collection source"/></label><label>Example post / image URL<input type="text" bind:value={form.example} maxlength="2000" placeholder="https://ganknow.com/post/…"/><small>Public HTTPS links only. Changing this clears previews linked to the old example.</small></label><label>Notes<textarea bind:value={form.notes} maxlength="10000" rows="3" placeholder="Anything worth keeping with this set"></textarea></label><label class="upload-label"><Upload size={18}/><span>{files.length?`${files.length} image${files.length>1?'s':''} selected`:'Add images (2–5 per set)'}</span><input type="file" accept="image/jpeg,image/png,image/gif,image/webp" multiple aria-label="Preview images" onchange={e=>files=Array.from(e.currentTarget.files||[])}/></label><p class="form-help">Each set needs 2–5 distinct images, 12 MiB each. New uploads are added to existing images. Without uploads, a public example link can supply images. Sets with fewer than 2 stay marked incomplete.</p>{#if error}<div class="alert error" role="alert">{error}</div>{/if}<div class="editor-footer"><button type="button" class="text-btn" disabled={busy} onclick={()=>editor=false}>Cancel</button><button class="primary" disabled={busy||extracting}>{#if busy}<LoaderCircle size={16} class="spin"/>{:else}<Check size={16}/>{/if}{busy?'Saving…':'Save image set'}</button></div></form></dialog>{/if}

{#if importPreview}
 <dialog class="import-review" use:modal oncancel={e=>{e.preventDefault();if(!busy)importPreview=null;}} aria-labelledby="import-review-title">
  <div class="editor-heading"><div><span class="eyebrow">REVIEW BEFORE SAVING</span><h2 id="import-review-title">Review import results.</h2></div><button class="icon-btn" aria-label="Close import preview" disabled={busy} onclick={()=>importPreview=null}><X size={20}/></button></div>
  <p class="review-note">No changes have been saved. Confirm to apply this snapshot and fetch up to 5 images for new or changed example links.</p>
  <div class="report review-counts"><div><strong>{importPreview.report.created}</strong><span>NEW SETS</span></div><div><strong>{importPreview.report.changed}</strong><span>CHANGED</span></div><div><strong>{importPreview.report.unchanged}</strong><span>UNCHANGED</span></div><div><strong>{importPreview.report.scanCandidates.length}</strong><span>FETCH IMAGES</span></div></div>
  <p class="review-source">{importPreview.sheetUrl}</p>
  {#if importPreview.report.changes.length}
   <div class="review-table"><table><thead><tr><th>CHANGE</th><th>IMAGE SET</th><th>ARTIST / DATE</th><th>DETAILS</th></tr></thead><tbody>{#each importPreview.report.changes as change}<tr><td><span class="status-tag {change.kind==='new'?'ready':'pending'}">{change.kind==='new'?'New':'Update'}</span></td><td>{change.after.title}{#if change.before}<small class="previous-value">set_id: {change.id}</small>{/if}{#if change.before&&change.before.title!==change.after.title}<small class="previous-value">Was: {change.before.title}</small>{/if}</td><td>{change.after.group}<small class="previous-value">{change.after.date||'Unknown date'}</small></td><td><span class="review-example">{change.after.example||'No example link'}</span>{#if change.before&&change.before.example!==change.after.example}<small class="preview-warning">Example changed: existing images will be cleared and fetched again.</small>{/if}{#if change.after.importWarning}<small class="preview-warning">{change.after.importWarning}</small>{/if}<details><summary>View all fields</summary>{#each ['title','group','date','source','example','notes'] as field}<div class="review-field"><strong>{field}</strong>{#if change.before&&change.before[field]!==change.after[field]}<span class="previous-value">Before: {change.before[field]||'—'}</span>{/if}<span>{change.after[field]||'—'}</span></div>{/each}</details></td></tr>{/each}</tbody></table></div>
  {:else}<p class="review-note">No new sets or metadata changes found. Existing images will be retained.</p>{/if}
  {#if error}<div class="alert error" role="alert">{error}</div>{/if}
  <div class="editor-footer"><button class="text-btn" disabled={busy} onclick={()=>importPreview=null}>Cancel</button><button class="primary" disabled={busy} onclick={confirmImport}>{#if busy}<LoaderCircle size={16} class="spin"/>Updating…{:else}<Check size={16}/>OK — Update{/if}</button></div>
 </dialog>
{/if}
